### ISSUE TITLE
When you click Wallet on left menu, show spinner until wallet is loaded

### ISSUE THREAD

**Issue by Warchant** [ggxchain/rfq-ui#31]

**Comment by AuroraLantean** [comment]
I have added loading file and suspense wrapping tokenlist in Dex, Wallet, Transfer pages, using existing loading spinner in the component folder.
Because we do not have huge data, the loading delay is difficult to be observed...

**Comment by AuroraLantean** [comment]
add spinner during initial loading token list on Wallet and Transfers pages

**Comment by AuroraLantean** [comment]
I have added loading files and Suspense wrapping Tokenlist in Wallet and Transfer pages, Suspense wrapping OrderBook and OrderList in Dex page. But they are not working because the TokenList, OrderBook, and OrderList themselves do not fetch async data inside themselves, hence Suspense loading do not get triggered.
As a workaround, I added some states in those pages to manually trigger the loading spinner to show initially. Moving async code into Tokenlist, OrderBook, OrderList would be a big change in the future.
See result demo: https://drive.google.com/file/d/1-0Z6xE5YZdwmYON4VFLcWgZ3IukganyG/view?ts=66179532
Dex page OrderList(My orders) has not been added with my manual loading trigger. please advise. Thanks

**Comment by AuroraLantean** [comment]
Ok. CI test failed: expect(screen.getByText("No tokens found")).toBeInTheDocument();
I think it is because it would show the spinner first, then "No tokens found" soon later

https://github.com/ggxchain/rfq-ui/actions/runs/8647873606/job/23710356192?pr=38

**Comment by AuroraLantean** [comment]
All spaces and tests have been fixed. Please approve https://github.com/ggxchain/rfq-ui/pull/38
